apiVersion: apps/v1
kind: Deployment
metadata:
  name: gensen
  labels:
    app: gensen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      annotations:
        vpc.amazonaws.com/pod-eni: "true"
        vpc.amazonaws.com/pod-eni-sg: "${pod_sg_id}"
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  labels:
    app: my-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-abc12345,subnet-def67890
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-app-svc
                port:
                  number: 80