apiVersion: apps/v1
kind: Deployment
metadata:
  name: gensen
  labels:
    app: gensen
spec:
  replicas: 1
  selector:
    matchLabels:
      app:
  template:
    metadata:
      annotations:
        vpc.amazonaws.com/pod-eni: "true"
        vpc.amazonaws.com/pod-eni-sg: "sg-0e5aafe417c93b626"
      labels:
        app: gensen
    spec:
      containers:
        - name: gensen
          image: 
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gensen-svc
  labels:
    app: gensen
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: gensen
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gensen-ingress
  labels:
    app: gensen
  namespace: gensen
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-004334dbc180cd055,subnet-0f5d7dd265e46c8af,subnet-0762ad1c9e0b988dc
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gensen-svc
                port:
                  number: 80