apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name | quote }}
  namespace: {{ .Values.app.name | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name | quote }}
    spec:
      dnsPolicy: Default
      serviceAccountName: cluster-admin
      containers:
        - name: {{ .Values.app.name | quote }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          ports:
            - containerPort: {{ .Values.app.port }}
          envFrom:
            - secretRef:
                name: {{ .Values.app.name | quote}}
            - configMapRef:
                name: {{ .Values.app.name | quote }}