apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name | quote}}
  namespace: {{ .Values.app.name | quote }}
  labels:
    app: {{ .Values.app.name | quote }}
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: {{ .Values.aws.public_subnets | quote }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.aws.alb.security_group_id | quote }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.aws.alb.acm_cert_arn | quote }}
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name | quote }}
                port:
                  number: {{ .Values.app.port }}