apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name | quote }}
  namespace: {{ .Values.app.name | quote }}
  labels:
    app: {{ .Values.app.name | quote }}
spec:
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name | quote }}
  type: NodePort