name: Destroy Infrastructure - Test

on:
  workflow_dispatch:

jobs:
  destroy:
    name: destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_WORKING_DIR: tech-exercise/test

    permissions:
      contents: read
      actions: write

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: state download
        uses: badgerhobbs/terraform-state@v2
        with:
          operation: download
          location: artifact
          directory: ${{ env.TF_WORKING_DIR }}
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
        continue-on-error: true

      - name: init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: destroy
        id: destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform destroy -auto-approve \
            -var="app_name=${{ vars.APP_NAME }}" \
            -var="region=${{ vars.AWS_REGION }}" \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="key_name=${{ secrets.KEY_NAME }}"

      - name: destroy output
        if: success()
        run: |
          echo "### Infrastructure Destruction Report" > destruction_report.md
          echo "" >> destruction_report.md
          echo "Infrastructure was successfully destroyed at $(date)" >> destruction_report.md
          echo "" >> destruction_report.md
          echo "Workspace: default" >> destruction_report.md
          echo "" >> destruction_report.md
          echo "Initiated by: ${{ github.actor }}" >> destruction_report.md

      - name: destroy output upload
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-report-${{ github.run_id }}
          path: destruction_report.md
          retention-days: 30

      - name: destroy error
        if: failure()
        run: |
          echo "### Infrastructure Destruction Failed" > destruction_error.md
          echo "" >> destruction_error.md
          echo "Failed to destroy infrastructure at $(date)" >> destruction_error.md
          echo "" >> destruction_error.md
          echo "Initiated by: ${{ github.actor }}" >> destruction_error.md
          echo "" >> destruction_error.md
          echo "Please check the logs for more details." >> destruction_error.md

      - name: destroy upload error
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-destroy-error-${{ github.run_id }}
          path: destruction_error.md
          retention-days: 30

      - name: state upload
        uses: badgerhobbs/terraform-state@v2
        if: always()
        with:
          operation: upload
          location: artifact
          directory: ${{ env.TF_WORKING_DIR }}
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
