name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    name: destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      TF_WORKING_DIR: tech-exercise/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4

      - name: AWS Configure
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init

      - name: Destroy
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform destroy -auto-approve \
            -var="app_name=${{ secrets.APP_NAME }}" \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="key_name=${{ secrets.KEY_NAME }}"